tap "brandonskerritt/rustscan"
tap "brewsci/science"
tap "derailed/k9s"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "sidaf/pentest"
brew "bat"
brew "readline"
brew "binwalk"
brew "cmake"
brew "coreutils"
brew "exiftool"
brew "exploitdb"
brew "fd"
brew "ffuf"
brew "fish"
brew "git"
brew "gnuplot"
brew "libtool"
brew "libevent"
brew "go"
brew "gobuster"
brew "htop"
brew "httpie"
brew "hydra"
brew "imagemagick"
brew "iproute2mac"
brew "jq"
brew "jython"
brew "kubernetes-cli"
brew "libconfig"
brew "lnav"
brew "make"
brew "mas"
brew "mysql"
brew "netcat"
brew "nmap"
brew "node"
brew "openfortivpn"
brew "openvpn"
brew "pstree"
brew "ripgrep"
brew "rustscan"
brew "sqlmap"
brew "starship"
brew "terminal-notifier"
brew "tmux"
brew "tnftp"
brew "tree"
brew "vim"
brew "derailed/k9s/k9s"
brew "heroku/brew/heroku"
brew "sidaf/pentest/sec_lists"
cask "adoptopenjdk8"
cask "dbeaver-community"
cask "docker"
cask "firefox"
cask "font-fira-code-nerd-font"
cask "ghidra"
cask "google-chrome"
cask "iterm2"
cask "logitech-options"
cask "metasploit"
cask "microsoft-teams"
cask "notion"
cask "postman"
cask "slite"
cask "spotify"
cask "sublime-text"
cask "termius"
cask "vagrant"
cask "visual-studio-code"
cask "wireshark"
cask "xquartz"
cask "zoomus"
mas "1Password 7", id: 1333542190
mas "Ghostery Lite", id: 1436953057
mas "Grammarly for Safari", id: 1462114288
mas "iStat Menus", id: 1319778037
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft To Do", id: 1274495053
mas "Microsoft Word", id: 462054704
mas "Xcode", id: 497799835
